#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/lalune

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/lalune/settings.json /etc/lalune/configs.json
    procd_close_instance
}

stop_service() {
    # Убедимся, что ядро и TUN прибраны
    ip link del csqtt0 2>/dev/null || true
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "lalune"
}
