allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

// ВАЖНО: KGP 1.9.24, иначе kotlin-stdlib 1.9.x не соберётся.
ext.kotlin_version = '1.9.24'

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
