// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfigsJson() {
  return window['go']['main']['App']['GetConfigsJson']();
}

export function GetLogsJson() {
  return window['go']['main']['App']['GetLogsJson']();
}

export function GetSettingsJson() {
  return window['go']['main']['App']['GetSettingsJson']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetConfigsCallback(arg1) {
  return window['go']['main']['App']['SetConfigsCallback'](arg1);
}

export function SetLogCallback(arg1) {
  return window['go']['main']['App']['SetLogCallback'](arg1);
}

export function SetStatusCallback(arg1) {
  return window['go']['main']['App']['SetStatusCallback'](arg1);
}

export function SetUpdateCallback(arg1) {
  return window['go']['main']['App']['SetUpdateCallback'](arg1);
}

export function UpdateCore() {
  return window['go']['main']['App']['UpdateCore']();
}
