// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs():Promise<boolean>;

export function Connect(arg1:number):Promise<boolean>;

export function DeleteConfig(arg1:number):Promise<boolean>;

export function Disconnect():Promise<boolean>;

export function GetConfigsJson():Promise<string>;

export function GetLogsJson():Promise<string>;

export function GetSettingsJson():Promise<string>;

export function SaveConfig(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:string):Promise<boolean>;

export function SetConfigsCallback(arg1:any):Promise<void>;

export function SetLogCallback(arg1:any):Promise<void>;

export function SetStatusCallback(arg1:any):Promise<void>;

export function SetUpdateCallback(arg1:any):Promise<void>;

export function UpdateCore():Promise<boolean>;
