name: iOS сборка

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Тип сборки'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
         
